### ISSUE TITLE
You jest? It's not even pronounceable!

### ISSUE THREAD

**Issue by impredicative** [pyrustic/jesth#1]
How is one supposed to pronounce "jesth" in a meeting? It's not possible. Why not call it JAML, etc.? Also, people don't want to use anything have to do with "hack" in a professional setting, even in a good meaning of the word.

**Comment by pyrustic** [comment]
Hi !

I would like to know what **JAML** stands for (Just Another Markup Language ? JAML Ain't Markup Language ?). 

About the pronunciation, I updated the [Overview](https://github.com/pyrustic/jesth#overview) section of the README to include this detail.

**Comment by impredicative** [comment]
JAML = Just Add Musings & Load

**Comment by pyrustic** [comment]
Anyway, **JAML** looks just like **YAML** ! That alone is a good reason not to accept this suggestion...

**Comment by impredicative** [comment]
It's not a suggestion for JAML. It's a suggestion to think about a name that's obviously and easily pronounceable without being told how to do it. A thousand different names are possible.

**Comment by pyrustic** [comment]
I still find [/dʒest/](https://dictionary.cambridge.org/pronunciation/english/jest) cool. Let's say it will be like a kind of private joke, the insiders will know how to pronounce it, the new ones will only do it once initiated. Think [Vanilla.js](http://vanilla-js.com/) and all the fun stuff deliberately or inadvertently inserted into technical stuff ;)
